### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by heshriti** [cvxgrp/cvxportfolio#30]
Hi,

I've installed the packages pip. That's the only way I could get this package installed. 
Can this package be updated with working examples please.

In the Singleperiod example, 

simulated_tcost = cp.TcostModel(half_spread=0.0005/2., nonlin_coeff=1., sigma=sigmas, volume=volumes)

I get a ValueError as follows:
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by joseortiz3** [comment]
Please provide the whole stack trace, not just the error message.

**Comment by heshriti** [comment]
Traceback (most recent call last):
  File "SinglePeriodOptimization.py", line 34, in <module>
    simulated_tcost = cp.TcostModel(half_spread=0.0005/2., nonlin_coeff=1., sigma=sigmas, volume=volumes)
  File "/usr/home/cvxportfolio/costs.py", line 143, in __init__
    null_checker(sigma)
  File "/usr/home/cvxportfolio/utils/data_management.py", line 29, in null_checker
    if np.any(pd.isnull(obj)):
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
