### ISSUE TITLE
Helloworld issue

### ISSUE THREAD

**Issue by semiter1** [cvxgrp/cvxportfolio#58]
Hello, I installed the CVXPY and CVXPortfolio. When I run the Helloworld example, I got the following error message. 

I am using windows 10, the CVXportfolio version is 0.0.12. Can someone know how to resolve this issue?  Thanks!

```
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\multiprocess\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\multiprocess\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxportfolio\simulator.py", line 147, in _run_backtest
    policy, loglevel=loglevel)
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxportfolio\simulator.py", line 116, in run_backtest
    u = policy.get_trades(h, t)
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxportfolio\policies.py", line 266, in get_trades
    cost_expr, const_expr = cost.weight_expr(t, wplus, z, value)
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxportfolio\risks.py", line 58, in weight_expr
    self.expression = self._estimate(t, w_plus - self.w_bench, z, value)
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxportfolio\risks.py", line 105, in _estimate
    wplus, values_in_time(self.Sigma, t))
  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\atoms\quad_form.py", line 218, in quad_form
    raise Exception("Invalid dimensions for arguments.")
Exception: Invalid dimensions for arguments.
"""


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-2-0cb7372edff0>", line 6, in <module>
    policies=[spo_policy, cp.Hold()])

  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxportfolio\simulator.py", line 152, in run_multiple_backtest
    results = workers.map(_run_backtest, policies)

  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\multiprocess\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "C:\Users\jxl128031\AppData\Local\Continuum\anaconda3\lib\site-packages\multiprocess\pool.py", line 657, in get
    raise self._value

Exception: Invalid dimensions for arguments.
```

**Comment by southwest-git** [comment]
I suspect it has to do with the deprecation of pd.Panel. I tried updating this line in their Helloworld and it works now.

risk_model = cp.FullSigma(Sigma_hat.reset_index(level=1, drop=True))

Hope this helps.

**Comment by hujrsmatrix** [comment]
> I suspect it has to do with the deprecation of pd.Panel. I tried updating this line in their Helloworld and it works now.
> 
> risk_model = cp.FullSigma(Sigma_hat.reset_index(level=1, drop=True))
> 
> Hope this helps.

It works! thank you

**Comment by enzbus** [comment]
The `pd.Panel` bug is fixed now.
